# Generated by Django 3.2.8 on 2021-11-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitudes', models.CharField(max_length=50)),
                ('valor', models.IntegerField(max_length=10)),
            ],
        ),
    ]
