# Generated by Django 3.2.8 on 2021-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demohmi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valores',
            name='magnitudes',
        ),
        migrations.AddField(
            model_name='valores',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='descrpcion'),
        ),
        migrations.AddField(
            model_name='valores',
            name='parametros',
            field=models.CharField(default=10, max_length=100, verbose_name='parametro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valores',
            name='valor',
            field=models.IntegerField(verbose_name='valor'),
        ),
    ]
